name: EOD-test

on: 
  schedule:
    - cron: "0 23 * * *"  # UTC 23:00 everyday
  workflow_dispatch: {}

defaults:
  run:
    shell: powershell

jobs:
  full-test:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix: 
        branch: [dev, main]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - name: Build test image
        run: docker build --target test -t "oram-main:eod_test-${{ matrix.branch }}" .
      - name: Run full tests
        run: docker run --rm "oram-main:eod_test-${{ matrix.branch }}"